# Generated by Django 5.2.5 on 2025-08-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_mail',
            new_name='student_email',
        ),
    ]
