# Generated by Django 5.2.5 on 2025-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SAqemgBvatXqqfzHWIYGBU8nXfrMXpFM', editable=False, max_length=32, unique=True),
        ),
    ]
