# Generated by Django 5.0 on 2025-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='PZFrwTHmTYrwcUCTTf6HYt5xJmINg0go', editable=False, max_length=32, unique=True),
        ),
    ]
