# Generated by Django 5.2.5 on 2025-08-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FebTlrRL9GetFpVeHcmpXzVHFuJjalQc', editable=False, max_length=32, unique=True),
        ),
    ]
