# Generated by Django 5.2.5 on 2025-08-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rTD8GwIqzbuNmaHlwLea9GAGi6QwHFUN', editable=False, max_length=32, unique=True),
        ),
    ]
