# Generated by Django 5.2.5 on 2025-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ujh11xj7j0CnTAa8xcCGWQ5tXoCZFFcC', editable=False, max_length=32, unique=True),
        ),
    ]
